---
title: "Cribbage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Packages
```{r, warning=FALSE}
library(ggplot2)
library(ggthemes)
```

# Setting Parameters for sin functions
```{r}
ls = 1:144 # list of all dots including stop points
u = 8
b = (u-0)/144
r = (u-0)/144
a = 2.5
t = 0
w = (u-0)/144
```

# Functions
```{r}
#Finding Blue X Values
list_b = 
  function(ARGUMENT) {
    VALUE = b * ls
    return(VALUE)
  }
blue_x = list_b(b)

#Finding Red X Values
list_r = 
  function(ARGUMENT) {
    VALUE = r * ls
    return(VALUE)
  }
red_x = list_r(r)


#Finding Blue Y Values
blue = 
  function(ARGUMENT) {
    VALUE = sin(a * list_b(b) + t) + 1.125
    return(VALUE)
  }
blue_y_original = blue(list_b(b))
blue_y = blue(list_b(b))
blue_y[seq(6,144,6)] = NA # eliminates holes where we want spaces

#Finding Red Y Values
red = 
  function(ARGUMENT) {
    VALUE2 = sin(a * list_r(r) + t) + 1
    return(VALUE2)
  }
red_y_original = red(list_r(r))
red_y = red(list_r(r))
red_y[seq(6,144,6)] = NA # eliminates holes where we want spaces


#Finding Stopping Values

#Finding Blue Stopping X Values
blue_stoppers_x = 
  function(ARGUMENT) {
    VALUE = w * seq(6,144,6)
    return(VALUE)
  }
blue_stop_x = blue_stoppers_x(w)

#Finding Blue Stopper Y Values
blue_stoppers_y = 
  function(ARGUMENT) {
    VALUE = sin(a * blue_stoppers_x(w) + t) + 1.125
    return(VALUE)
  }
blue_stop_y = blue_stoppers_y(blue_stoppers_x(w))

#Finding Red Stopping X Values
red_stoppers_x = 
  function(ARGUMENT) {
    VALUE = w * seq(6,144,6)
    return(VALUE)
  }
red_stop_x = red_stoppers_x(w)

#Finding Red Stopper Y Values
red_stoppers_y = 
  function(ARGUMENT) {
    VALUE = sin(a * red_stoppers_x(w) + t) + 1
    return(VALUE)
  }
red_stop_y = red_stoppers_y(red_stoppers_x(w))
```

# Garbage Code
```{r, echo=FALSE}
#Old Data Frames

# names(wd)[1] = "input"
# names(wd)[2] = "output"
# names(wd)[3] = "col_input"
# 
# data = data.frame(blue_x,red_x,blue_y,red_y)
# df = cbind(stack(data[1:2]), stack(data[3:4]))
# names(df)[1] = "input"
# names(df)[2] = "col_input"
# names(df)[3] = "output"
# names(df)[4] = "col_output"
# df

# vec_w = c("white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white","white")
```

# Data Frames
```{r}
stp_blue = data.frame(blue_stop_x,blue_stop_y)
wd = data.frame(red_stop_x,red_stop_y)
blue_data = data.frame(blue_x,blue_y)
red_data = data.frame(red_x,red_y)
blue_data_clean = data.frame(blue_x,blue_y_original)
red_data_clean = data.frame(red_x,red_y_original)
```

# Plot
```{r, warning=FALSE}
# Parameters for plot
s = 0.65
alph_line = 0.5
alph_point = 5

board = ggplot() + 
    geom_hline(yintercept = seq(0,2,0.5), color = "gray42") +
    geom_vline(xintercept = seq(0,8,1), color = "gray42") +
    geom_point(data = blue_data, 
               aes(x=blue_x,y=blue_y), 
               color = "blue", 
               size = s, 
               alpha = alph_point) +
    geom_point(data = red_data, 
               aes(x=red_x,y=red_y), 
               color = "red", 
               size = s, 
               alpha = alph_point) +
    geom_line(data = blue_data_clean, 
              aes(x=blue_x,y=blue_y_original), 
              color = "blue", 
              size = s, 
              alpha = alph_line) +
    geom_line(data = red_data_clean, 
              aes(x=red_x,y=red_y_original), 
              color = "red", 
              size = s, 
              alpha = alph_line) +
    geom_point(data = wd, 
               aes(x=red_stop_x,y=red_stop_y), 
               color = "black", 
               size = 0.15, 
               alpha = 5) +
    geom_point(data = stp_blue, 
               aes(x=blue_stop_x,y=blue_stop_y), 
               color = "black", 
               size = 0.15, 
               alpha = 5) +
    scale_x_continuous(breaks = seq(0,8,2), 
                       limits = c(0,8), 
                       expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0,2,1), 
                       limits = c(-0.025,2.15), 
                       expand = c(0, 0)
                       ) #might want to hard code max(blue_y)*1.05

board + 
  # theme_solarized_2(light = FALSE) + # Potential Theme
  theme(panel.background = element_rect(fill = "gray69"),
        axis.title.x = element_blank(),axis.title.y=element_blank(), # Removes Axis Title
        axis.text.x=element_blank(),axis.text.y=element_blank(),  # Removes Axis Numbers 
        axis.ticks.x=element_blank(),axis.ticks.y=element_blank())# Removes Axis Ticks
        # scale_x_continuous(limits = c(0,8), expand = c(0, 0)) + # Trims Extra Parts of Graph
        

aspect_ratio <- 3 # Not Sure why but 3 scales us to 4 better than 4 does:(
height <- 2
ggsave("board.png", height = 2 , width = 2 * aspect_ratio)
```

